"""empty message

Revision ID: 284063115099
Revises: 672f7c0c62a1
Create Date: 2017-06-12 05:36:01.341796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284063115099'
down_revision = '672f7c0c62a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_locations', sa.Column('latlng', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_locations', 'latlng')
    # ### end Alembic commands ###
