"""empty message

Revision ID: 672f7c0c62a1
Revises: 22ebd369454e
Create Date: 2017-06-12 03:50:52.489351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672f7c0c62a1'
down_revision = '22ebd369454e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_locations', sa.Column('country', sa.String(length=64), nullable=True))
    op.add_column('user_locations', sa.Column('name', sa.String(length=256), nullable=True))
    op.add_column('user_locations', sa.Column('pin', sa.String(length=64), nullable=True))
    op.add_column('user_locations', sa.Column('state', sa.String(length=64), nullable=True))
    op.add_column('user_locations', sa.Column('street', sa.String(length=64), nullable=True))
    op.drop_column('user_locations', 'location_str')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_locations', sa.Column('location_str', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('user_locations', 'street')
    op.drop_column('user_locations', 'state')
    op.drop_column('user_locations', 'pin')
    op.drop_column('user_locations', 'name')
    op.drop_column('user_locations', 'country')
    # ### end Alembic commands ###
